/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedb;

import com.jaunt.ResponseException;
import com.jaunt.UserAgent;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Reza Elborneo
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        Date datenow = Calendar.getInstance().getTime();
        SpinnerDateModel smb = new SpinnerDateModel(datenow, null, null, 11);
        this.spinerDateTime.setModel(smb);
        JSpinner.DateEditor d = new JSpinner.DateEditor(this.spinerDateTime, "dd-MM-yyyy HH:mm:ss");
        this.spinerDateTime.setEditor(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIMDUrl = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlot = new javax.swing.JTextArea();
        txtYear = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        txtRuntime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDirectors = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCast = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCountries = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtGenres = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtThrailer = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtKeywords = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtWriter = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelPoster = new javax.swing.JPanel();
        lblPoster = new javax.swing.JLabel();
        txtPoster = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtStreamCode = new javax.swing.JTextField();
        txtDownlink = new javax.swing.JTextField();
        cmbQuality = new javax.swing.JComboBox();
        cmbResolution = new javax.swing.JComboBox();
        txtFileSize = new javax.swing.JTextField();
        cmbSizeUnit = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtGPhotos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtFileName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        txtPostURL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        spinerDateTime = new javax.swing.JSpinner();
        cmbPostStatus = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOVIEDB");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("IMDB ID :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("TITLE :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("PLOT :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("YEAR/RATING : ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("CAST :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("DIRECTORS :");

        txtIMDUrl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtIMDUrl.setText("tt4046784");

        txtTitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtPlot.setColumns(20);
        txtPlot.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPlot.setLineWrap(true);
        txtPlot.setRows(1);
        jScrollPane1.setViewportView(txtPlot);

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtRating.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtRuntime.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtDirectors.setColumns(20);
        txtDirectors.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtDirectors.setRows(1);
        jScrollPane2.setViewportView(txtDirectors);

        txtCast.setColumns(20);
        txtCast.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCast.setRows(1);
        jScrollPane3.setViewportView(txtCast);

        txtCountries.setColumns(20);
        txtCountries.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCountries.setRows(1);
        jScrollPane4.setViewportView(txtCountries);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("COUNTRY :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("POSTER :");

        txtGenres.setColumns(20);
        txtGenres.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtGenres.setRows(1);
        jScrollPane6.setViewportView(txtGenres);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("GENRE :");

        txtThrailer.setColumns(20);
        txtThrailer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtThrailer.setRows(1);
        jScrollPane7.setViewportView(txtThrailer);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("TRAILER :");

        txtKeywords.setColumns(20);
        txtKeywords.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtKeywords.setRows(1);
        jScrollPane8.setViewportView(txtKeywords);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("KEYWORD :");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setText("GET DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("WRITERS :");

        txtWriter.setColumns(20);
        txtWriter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtWriter.setRows(1);
        jScrollPane9.setViewportView(txtWriter);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton3.setText("CHECK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("CHECK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        panelPoster.setBackground(new java.awt.Color(0, 0, 0));

        lblPoster.setBackground(new java.awt.Color(0, 0, 0));
        lblPoster.setText("poster");

        javax.swing.GroupLayout panelPosterLayout = new javax.swing.GroupLayout(panelPoster);
        panelPoster.setLayout(panelPosterLayout);
        panelPosterLayout.setHorizontalGroup(
            panelPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPoster, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        panelPosterLayout.setVerticalGroup(
            panelPosterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton6.setText("SPIN PLOT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton5))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIMDUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPoster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtRating, txtRuntime, txtYear});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtIMDUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jLabel10))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRuntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)))
                    .addComponent(panelPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtStreamCode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        txtDownlink.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        cmbQuality.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbQuality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BluRay", "CAM", "DVD-RIP", "HD-RIP", "HD-TS", "HD-TV", "N/A", "SCREENER", "TS", "TVRip", "WEB-DL", "WEB-RIP" }));

        cmbResolution.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbResolution.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "720p", "1080p", "N/A" }));

        txtFileSize.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        cmbSizeUnit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSizeUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MB", "GB" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setText("GPHOTOS :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setText("DL LINK :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel18.setText("QUALITY :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setText("SIZE :");

        txtGPhotos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel21.setText("VIDEO LINK :");

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton4.setText("FETCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("NAME :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(55, 55, 55)
                        .addComponent(txtFileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbQuality, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStreamCode, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDownlink, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(txtStreamCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDownlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cmbResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtFileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSizeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtLog.setRows(5);
        jScrollPane10.setViewportView(txtLog);

        txtPostURL.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPostURL.setText("http://www.movietrex.com/privateposter.php");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setText("Post URL :");

        cmbPostStatus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbPostStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POST NOW", "SCHEDULE" }));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton2.setText("POST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spinerDateTime)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPostStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtPostURL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbPostStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinerDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtCast.setText("");
        txtCountries.setText("");
        txtDirectors.setText("");
        txtGenres.setText("");
        txtKeywords.setText("");
        txtLog.setText("");
        txtPlot.setText("");
        txtPoster.setText("");
        txtRating.setText("");
        txtRuntime.setText("");
        txtRuntime.setText("");
        txtThrailer.setText("");
        txtTitle.setText("");
        txtWriter.setText("");
        txtYear.setText("");

        MovieDB mdb = new MovieDB(txtIMDUrl.getText(), this);
        mdb.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        txtCast.setText("");
        txtCountries.setText("");
        txtDirectors.setText("");
        txtGenres.setText("");
        txtKeywords.setText("");
        txtLog.setText("");
        txtPlot.setText("");
        txtPoster.setText("");
        txtRating.setText("");
        txtRuntime.setText("");
        txtRuntime.setText("");
        txtThrailer.setText("");
        txtWriter.setText("");
        txtYear.setText("");

        progress.setValue(0);
        progress.setIndeterminate(true);

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                UserAgent userAgent = new UserAgent();
                try {
                    txtLog.append("Checking similiar post...\n");
                    userAgent.sendGET(txtPostURL.getText() + "?check=" + URLEncoder.encode(txtTitle.getText(), "UTF-8"));
                    txtLog.append(userAgent.doc.innerHTML(1).replace("<br>", ""));
                    txtLog.append("\n");
                } catch (ResponseException localResponseException) {
                    txtLog.append(localResponseException.getMessage() + "\n");
                } catch (UnsupportedEncodingException ex) {
                    txtLog.append(ex.getMessage() + "\n");
                }
                txtLog.append("DONE");

                progress.setIndeterminate(false);
                progress.setValue(100);
            }
        });
        t.start();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PostProcess p = new PostProcess(this);
        p.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        txtDownlink.setText("");
        txtStreamCode.setText("");

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {

                progress.setValue(0);
                progress.setIndeterminate(true);

                UserAgent userAgent = new UserAgent();
                try {
                    txtLog.append("Fetch stream link...\n");
                    userAgent.sendGET(txtGPhotos.getText());
                    String vidLink = userAgent.doc.innerHTML().split("property=\"og:image\" content=\"")[1].split("=")[0];
                    txtStreamCode.setText(vidLink);
                    String downloadLink = userAgent.doc.innerHTML().split("https://video.googleusercontent.com")[1].split("\",")[0];
                    txtDownlink.setText("https://video.googleusercontent.com" + downloadLink);

                    String fileNameLink = userAgent.doc.innerHTML().split("https://lh3.googleusercontent.com/")[1].split("=w600")[0];
                    URL obj = new URL("https://lh3.googleusercontent.com/" + fileNameLink + "=w72-h39-k-rw-no");
                    URLConnection conn = obj.openConnection();
                    String filename = conn.getHeaderField("content-disposition");
                    getTxtFileName().setText(filename.split("\"")[1]);

                    if (filename.toLowerCase().contains("bluray") | filename.toLowerCase().contains("blu-ray")) {
                        cmbQuality.setSelectedItem("BluRay");
                    } else if (filename.toLowerCase().contains("webdl") | filename.toLowerCase().contains("web-dl")) {
                        cmbQuality.setSelectedItem("WEB-DL");
                    } else if (filename.toLowerCase().contains("webrip") | filename.toLowerCase().contains("web-rip")) {
                        cmbQuality.setSelectedItem("WEB-RIP");
                    } else if (filename.toLowerCase().contains("cam")) {
                        cmbQuality.setSelectedItem("CAM");
                    } else if (filename.toLowerCase().contains("dvdrip") | filename.toLowerCase().contains("dvd-rip")) {
                        cmbQuality.setSelectedItem("DVD-RIP");
                    } else if (filename.toLowerCase().contains("hdrip") | filename.toLowerCase().contains("hd-rip")) {
                        cmbQuality.setSelectedItem("HD-RIP");
                    } else if (filename.toLowerCase().contains("hdts") | filename.toLowerCase().contains("hd-ts")) {
                        cmbQuality.setSelectedItem("HD-TS");
                    } else if (filename.toLowerCase().contains("hdtv") | filename.toLowerCase().contains("hd-tv")) {
                        cmbQuality.setSelectedItem("HD-TV");
                    } else if (filename.toLowerCase().contains("screener")) {
                        cmbQuality.setSelectedItem("SCREENER");
                    } else if (filename.toLowerCase().contains("TS")) {
                        cmbQuality.setSelectedItem("TS");
                    } else if (filename.toLowerCase().contains("tvrip") | filename.toLowerCase().contains("tv-rip")) {
                        cmbQuality.setSelectedItem("TV-RIP");
                    } else {
                        cmbQuality.setSelectedItem("N/A");
                    }

                    if (filename.toLowerCase().contains("1080p") | filename.toLowerCase().contains("1080")) {
                        cmbResolution.setSelectedItem("1080");
                    } else if (filename.toLowerCase().contains("720p") | filename.toLowerCase().contains("720")) {
                        cmbQuality.setSelectedItem("720p");
                    } else {
                        cmbQuality.setSelectedItem("N/A");
                    }

                } catch (ResponseException localResponseException) {
                    txtLog.append(localResponseException.getMessage() + "\n");
                } catch (MalformedURLException ex) {
                    Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(FormUtama.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtLog.append("DONE\n\n");
                progress.setIndeterminate(false);
                progress.setValue(100);
            }
        });
        t.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            getLblPoster().setText("");
            URL url = new URL(getTxtPoster().getText());
            BufferedImage image = ImageIO.read(url);
            getLblPoster().setIcon(new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(getPanelPoster().getWidth(), getPanelPoster().getHeight(), Image.SCALE_DEFAULT)));

        } catch (MalformedURLException ex) {
            Logger.getLogger(MovieDB.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MovieDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        FormSearch fs = new FormSearch(this);
        fs.setVisible(true);
        this.setEnabled(false);
        fs.toFront();
        fs.setLocationRelativeTo(this);
        fs.setAlwaysOnTop(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        formSpinPlot fsp = new formSpinPlot(this);
        this.setEnabled(false);
        fsp.toFront();
        fsp.setLocationRelativeTo(this);
        fsp.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormUtama fu = new FormUtama();
                fu.setLocationRelativeTo(null);
                fu.setVisible(true);
            }
        });
    }

    public JTextArea getTxtCast() {
        return txtCast;
    }

    public void setTxtCast(JTextArea txtCast) {
        this.txtCast = txtCast;
    }

    public JTextArea getTxtCountries() {
        return txtCountries;
    }

    public void setTxtCountries(JTextArea txtCountries) {
        this.txtCountries = txtCountries;
    }

    public JTextField getTxtIMDUrl() {
        return txtIMDUrl;
    }

    public void setTxtIMDUrl(JTextField txtIMDUrl) {
        this.txtIMDUrl = txtIMDUrl;
    }

    public JTextArea getTxtKeywords() {
        return txtKeywords;
    }

    public void setTxtKeywords(JTextArea txtKeywords) {
        this.txtKeywords = txtKeywords;
    }

    public JTextArea getTxtPlot() {
        return txtPlot;
    }

    public void setTxtPlot(JTextArea txtPlot) {
        this.txtPlot = txtPlot;
    }

    public JTextField getTxtPoster() {
        return txtPoster;
    }

    public void setTxtPoster(JTextField txtPoster) {
        this.txtPoster = txtPoster;
    }

    public JTextField getTxtRating() {
        return txtRating;
    }

    public void setTxtRating(JTextField txtRating) {
        this.txtRating = txtRating;
    }

    public JTextField getTxtRuntime() {
        return txtRuntime;
    }

    public void setTxtRuntime(JTextField txtRuntime) {
        this.txtRuntime = txtRuntime;
    }

    public JTextArea getTxtThrailer() {
        return txtThrailer;
    }

    public void setTxtThrailer(JTextArea txtThrailer) {
        this.txtThrailer = txtThrailer;
    }

    public JTextField getTxtTitle() {
        return txtTitle;
    }

    public void setTxtTitle(JTextField txtTitle) {
        this.txtTitle = txtTitle;
    }

    public JTextField getTxtYear() {
        return txtYear;
    }

    public void setTxtYear(JTextField txtYear) {
        this.txtYear = txtYear;
    }

    public JTextArea getTxtWriter() {
        return txtWriter;
    }

    public void setTxtWriter(JTextArea txtWriter) {
        this.txtWriter = txtWriter;
    }

    public JTextArea getTxtLog() {
        return txtLog;
    }

    public void setTxtLog(JTextArea txtLog) {
        this.txtLog = txtLog;
    }

    public JComboBox<String> getCmbPostStatus() {
        return cmbPostStatus;
    }

    public void setCmbPostStatus(JComboBox<String> cmbPostStatus) {
        this.cmbPostStatus = cmbPostStatus;
    }

    public JSpinner getSpinerDateTime() {
        return spinerDateTime;
    }

    public void setSpinerDateTime(JSpinner spinerDateTime) {
        this.spinerDateTime = spinerDateTime;
    }

    public JTextField getTxtPostURL() {
        return txtPostURL;
    }

    public void setTxtPostURL(JTextField txtPostURL) {
        this.txtPostURL = txtPostURL;
    }

    public JTextArea getTxtDirectors() {
        return txtDirectors;
    }

    public void setTxtDirectors(JTextArea txtDirectors) {
        this.txtDirectors = txtDirectors;
    }

    public JTextArea getTxtGenres() {
        return txtGenres;
    }

    public void setTxtGenres(JTextArea txtGenres) {
        this.txtGenres = txtGenres;
    }

    public JProgressBar getProgress() {
        return progress;
    }

    public void setProgress(JProgressBar progress) {
        this.progress = progress;
    }

    public JComboBox getCmbQuality() {
        return cmbQuality;
    }

    public void setCmbQuality(JComboBox cmbQuality) {
        this.cmbQuality = cmbQuality;
    }

    public JComboBox getCmbResolution() {
        return cmbResolution;
    }

    public void setCmbResolution(JComboBox cmbResolution) {
        this.cmbResolution = cmbResolution;
    }

    public JComboBox getCmbSizeUnit() {
        return cmbSizeUnit;
    }

    public void setCmbSizeUnit(JComboBox cmbSizeUnit) {
        this.cmbSizeUnit = cmbSizeUnit;
    }

    public JTextField getTxtDownlink() {
        return txtDownlink;
    }

    public void setTxtDownlink(JTextField txtDownlink) {
        this.txtDownlink = txtDownlink;
    }

    public JTextField getTxtFileSize() {
        return txtFileSize;
    }

    public void setTxtFileSize(JTextField txtFileSize) {
        this.txtFileSize = txtFileSize;
    }

    public JTextField getTxtStreamCode() {
        return txtStreamCode;
    }

    public void setTxtStreamCode(JTextField txtStreamCode) {
        this.txtStreamCode = txtStreamCode;
    }

    public JTextField getTxtGPhotos() {
        return txtGPhotos;
    }

    public void setTxtGPhotos(JTextField txtGPhotos) {
        this.txtGPhotos = txtGPhotos;
    }

    public JLabel getLblPoster() {
        return lblPoster;
    }

    public void setLblPoster(JLabel lblPoster) {
        this.lblPoster = lblPoster;
    }

    public JPanel getPanelPoster() {
        return panelPoster;
    }

    public void setPanelPoster(JPanel panelPoster) {
        this.panelPoster = panelPoster;
    }

    public JTextField getTxtFileName() {
        return txtFileName;
    }

    public void setTxtFileName(JTextField txtFileName) {
        this.txtFileName = txtFileName;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbPostStatus;
    private javax.swing.JComboBox cmbQuality;
    private javax.swing.JComboBox cmbResolution;
    private javax.swing.JComboBox cmbSizeUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JPanel panelPoster;
    private javax.swing.JProgressBar progress;
    private javax.swing.JSpinner spinerDateTime;
    private javax.swing.JTextArea txtCast;
    private javax.swing.JTextArea txtCountries;
    private javax.swing.JTextArea txtDirectors;
    private javax.swing.JTextField txtDownlink;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtFileSize;
    private javax.swing.JTextField txtGPhotos;
    private javax.swing.JTextArea txtGenres;
    private javax.swing.JTextField txtIMDUrl;
    private javax.swing.JTextArea txtKeywords;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextArea txtPlot;
    private javax.swing.JTextField txtPostURL;
    private javax.swing.JTextField txtPoster;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRuntime;
    private javax.swing.JTextField txtStreamCode;
    private javax.swing.JTextArea txtThrailer;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextArea txtWriter;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
