/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moviedb;

import com.jaunt.JNode;
import com.jaunt.NotFound;
import com.jaunt.ResponseException;
import com.jaunt.UserAgent;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.ListModel;

/**
 *
 * @author Reza Elborneo
 */
public class FormSearch extends javax.swing.JFrame {

    FormUtama fu;

    /**
     * Creates new form FormSearch
     */
    public FormSearch() {
        initComponents();
    }

    FormSearch(FormUtama fu) {
        initComponents();
        this.fu = fu;
        if (!fu.getTxtFileName().getText().isEmpty()) {
            this.txtSearchTitle.setText(fu.getTxtFileName().getText()
                    .replace(".", " ")
                    .replace("mkv", "").toLowerCase());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchTitle = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSearch = new javax.swing.JList<>();
        lblIMDB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPoster = new javax.swing.JLabel();
        cmbTahunSearch = new javax.swing.JComboBox<>();
        progressSearch = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        lblYear = new javax.swing.JLabel();
        txtTitleResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtSearchTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchTitleKeyPressed(evt);
            }
        });

        btnSearch.setText("SUBMIT");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        listSearch.setAutoscrolls(false);
        listSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listSearch);

        lblIMDB.setText("IMDB");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblPoster.setText("poster");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbTahunSearch.setEditable(true);
        cmbTahunSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        jButton2.setText("APPLY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYear.setText("YEAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(cmbTahunSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblIMDB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblYear))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitleResult)))
                    .addComponent(progressSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSearchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTahunSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(txtTitleResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIMDB)
                            .addComponent(lblYear))
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearch, cmbTahunSearch, txtSearchTitle, txtTitleResult});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.fu.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
             
                progressSearch.setValue(0);
                progressSearch.setIndeterminate(true);
                UserAgent userAgent = new UserAgent();
                try {
                    StringBuilder url = new StringBuilder("http://www.myapifilms.com/imdb/idIMDB?");
                    url.append("title=").append(txtSearchTitle.getText().replace(" ", "+")).append("&");
                    url.append("token=d462d732-e083-4ce7-a294-2434b034c990&").append("format=json&")
                            .append("language=en-us&")
                            .append("limit=10&")
                            .append("filter=3");

                    if (!cmbTahunSearch.getSelectedItem().toString().isEmpty() && !cmbTahunSearch.getSelectedItem().toString().equals("N/A")) {
                        url.append("&year=").append(cmbTahunSearch.getSelectedItem().toString());
                    }

                    userAgent.visit(url.toString());

                    JNode movie = userAgent.json.findFirst("movies");
                    DefaultListModel listModel = new DefaultListModel();
                    for (JNode n : movie) {
                        try {
                            listModel.addElement(n.get("idIMDB").toString() + " ~ " + n.get("year").toString() + " ~ " + n.get("title").toString() + " ~ " + n.get("urlPoster").toString().replace("\\", ""));
                        } catch (Exception e) {
                        }
                    }
                    listSearch.setModel(listModel);
                    

                } catch (ResponseException | NotFound ex) {
                    Logger.getLogger(FormSearch.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                progressSearch.setValue(100);
                progressSearch.setIndeterminate(false);

            }
        });
        t.start();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void listSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSearchMouseClicked
        // TODO add your handling code here:
        txtTitleResult.setText(listSearch.getSelectedValue().split(" ~ ")[2]);
        lblIMDB.setText(listSearch.getSelectedValue().split(" ~ ")[0]);
        lblYear.setText(listSearch.getSelectedValue().split(" ~ ")[1]);
        lblPoster.setText("");

        try {
            URL url = new URL(listSearch.getSelectedValue().split(" ~ ")[3].trim());
            BufferedImage image = ImageIO.read(url);
            lblPoster.setIcon(new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(lblPoster.getWidth(), lblPoster.getHeight(), Image.SCALE_DEFAULT)));

        } catch (MalformedURLException ex) {
            Logger.getLogger(FormSearch.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormSearch.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listSearchMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fu.getTxtIMDUrl().setText(lblIMDB.getText());
        fu.setEnabled(true);
        fu.toFront();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSearchTitleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTitleKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btnSearchActionPerformed(null);
        }
    }//GEN-LAST:event_txtSearchTitleKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbTahunSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIMDB;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblYear;
    private javax.swing.JList<String> listSearch;
    private javax.swing.JProgressBar progressSearch;
    private javax.swing.JTextField txtSearchTitle;
    private javax.swing.JTextField txtTitleResult;
    // End of variables declaration//GEN-END:variables
}
